Feature/alarm clear service
GroupOfRobots/magician_ros2 pull request #4
Opened 2024-01-01 15:14 UTC by yRagax

Added a service for clearing Dobot alarms and fixed unpacking message from Dobot bug when receiving response.

2024-01-03 16:55 UTC, jkaniuka commented on dobot_alarm_clear/config/alarm_clear_params.yaml
W tym pliku nie ma żadnych parametrów, więc możesz go usunąć.

2024-01-03 17:03 UTC, jkaniuka commented on dobot_driver/dobot_driver/interface.py
> -        return self.send_only(request)
Wykorzystana jest tutaj metoda `send_only()`, ponieważ zgodnie z _Dobot Magician API Description V1.2.3_ wysłanie rozkazu **ClearAllAlarmsState** nie zwraca żadnej informacji w odpowiedzi. Nie ma więc potrzeby oczekiwania na odpowiedź, z której nic nie wyciągniemy.

2024-01-03 17:06 UTC, jkaniuka commented on dobot_driver/dobot_driver/interface.py
>          request = Message([0xAA, 0xAA], 2, 20, True, False, [], direction='out') #BUG
Ten #BUG nie jest związany ani z metodą `send()`, ani `send_only()`. Chodzi o to, że zgodnie z _Dobot Communication Protocol V1.1.5_ rozkaz  **ClearAllAlarmsState** ma przypisane ID=21. W rzeczywistości ID tego rozkazu to 20. Zidentyfikowałem ten błąd i poinformowałem o nim producenta, lecz od ponad roku nic z tym nie zrobili.

2024-01-03 17:08 UTC, jkaniuka commented on dobot_driver/dobot_driver/message.py
> +        # </BUGFIX>
Czy informacja zwrotna zwracana po przesłaniu **ClearAllAlarmsState** zawiera jakieś istotne informacje?

2024-01-03 17:17 UTC, jkaniuka commented on dobot_alarm_clear/dobot_alarm_clear/alarm_clear.py
- Dodanie tego serwisu ma uzasadnienie, jeżeli zaznaczysz, że należy go wykorzystywać **jedynie wtedy, gdy** został wcześniej kliknięty przycisk RESET z tyłu robota. Wszystkie inne stany alarmowe powinien obsługiwać sterownik wysokopoziomowy - głównie mam tu na myśli ograniczenia kinematyki (obsługiwane w pakiecie `dobot_kinematics`)
- Jak dodajesz nową funkcjonalność, musisz opisać ją w READMe tzn. do czego to służy + kiedy i jak stosować (przykład komendy z call'em do serwisu).

2024-01-03 17:21 UTC, jkaniuka commented on dobot_alarm_clear/package.xml
Nie ma potrzeby tworzyć osobnego pakietu na jeden node (i to tak krótki) - można ten node dorzucić do pakietu np. `dobot_diagnostics`, który związany jest z alarmami

2024-01-03 17:22 UTC, jkaniuka commented on dobot_alarm_clear/setup.py
Nie jest potrzebny nowy pakiet na jeden node.

2024-01-03 17:25 UTC, jkaniuka requested changes
Przejrzałem. Uwagi w komentarzach :wink:

2024-01-15 18:56 UTC, yRagax commented
Zgodnie z wcześniejszą rozmową, handling wiadomości zwrotnej czyszczenia alarmów oraz zastosowanie send() zamiast send_only() miało zostać nie tyle z powodu, że interesuje mnie pusta wiadomość zwrócona przez robota, tylko że nie odczytanie jej powoduje bugi z odczytywaniem innych wiadomości (tj. pojawiające się współrzędne końcówki dobota zamiast alarmów, jak pokazywałem w laboratorium). Innymi słowy lepiej odczytać puste i nic nie zrobić, niżeli nie odczytać w ogóle.

2024-03-19 17:13 UTC, closed without merging